Add no-var and prefer-const rules
valtech-nyc/eslint-config-valtech pull request #6
Opened 2017-04-22 01:51 UTC by aaccurso

This configuration will throw error upon usage of `var` to declare variables, helping to clarify the scope of a variable.

Also it will throw error when using `let` to declare variables that aren't reassigned post declaration, promoting the use of `const`.

Some interesting related articles:

- https://ponyfoo.com/articles/var-let-const
- https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

2017-04-22 02:01 UTC, mAAdhaTTah commented
Thoughts on setting [`"destructuring": "all"`](http://eslint.org/docs/rules/prefer-const#options)? Otherwise, def 👍.

2017-04-22 02:11 UTC, aaccurso commented
Didn't know that one, I vote 👍 . It will definitely sharpen our React's `render` methods.

2017-04-24 18:21 UTC, mAAdhaTTah requested changes

2017-04-24 18:21 UTC, mAAdhaTTah commented on index.js
> +        'prefer-const': 2,
Add `"destructuring": "all"` for `prefer-const` and you've got my approval.

2017-04-24 18:34 UTC, MichaelFoss commented
@aaccurso, I will approve this once the `"destructuring": "all"` has been added.

2017-04-24 18:41 UTC, aaccurso commented
Just so we are on the same page, are we talking about http://eslint.org/docs/rules/prefer-destructuring , right? Because that rule is called `prefer-destructuring`.
Or is it this plugin https://www.npmjs.com/package/eslint-plugin-destructuring ?
Cause I've used neither on a project so I think it'd be irresponsible on my part if I created a PR with something I haven't tried 😃

2017-04-24 18:43 UTC, mAAdhaTTah commented
@aaccurso See the link provided by my comment. It's an option for `prefer-const`.

2017-04-24 18:50 UTC, mAAdhaTTah approved these changes

2017-04-24 18:51 UTC, MichaelFoss approved these changes

2017-04-24 18:56 UTC, mAAdhaTTah commented
@MichaelFoss + me = 2 approvals. Merging this PR.

2017-04-24 18:56 UTC, merged