Add no-console and no-alert warning rules
valtech-nyc/eslint-config-valtech pull request #7
Opened 2017-04-22 02:04 UTC by aaccurso

This will promote usage of the debugger tools and avoid unwanted `console.log`'s in the code.

Whenever there is a good reason to use `console.log`, a comment should be added to the line/s affected.

i.e.
```javascript
// Provide simple feedback when the application finishes initialization
console.log('Server Started'); // eslint-disable-line no-console
```

2017-04-23 12:57 UTC, mAAdhaTTah commented
I think I'd prefer these to be errors, rather than just warnings, but I like including them.

2017-04-23 21:11 UTC, aaccurso commented
Yes, I guess I'm thinking of these as a friendly reminder not to commit them.

We can't deny the fact that some devs prefer it instead of debugging (I mean, in some situations it's even more comfy).

So forcing devs to use a `// eslint-disable-line` just to log something very quickly while developing could prove a bit cumbersome.

However, I don't think it's a bad idea to throw error.

Both have their pros and cons. Warning seems to do the trick in my current project, but we haven't tried throwing error 😄

2017-04-24 00:09 UTC, mAAdhaTTah commented
I think `alert` is pretty useless, so maybe make that an error and see what others think on `console`?

2017-04-24 00:48 UTC, aaccurso commented
Yes, I totally agree.

On Apr 23, 2017 21:09, "James DiGioia" <notifications@github.com> wrote:

> I think alert is pretty useless, so maybe make that an error and see what
> others think on console?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/valtech-nyc/eslint-config-valtech/pull/7#issuecomment-296499025>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADcbyQwJ8NxmL-rm9qhBHzJ1lkaEyKeaks5ry-gxgaJpZM4NE8Tp>
> .
>

2017-04-24 18:21 UTC, mAAdhaTTah requested changes

2017-04-24 18:21 UTC, mAAdhaTTah commented on index.js
> +        'no-alert': 1,
Make `no-alert` an error.

2017-04-24 18:42 UTC, MichaelFoss commented
How do you feel about [the options](http://eslint.org/docs/rules/no-console#options)?

2017-04-24 18:46 UTC, MichaelFoss commented
Good enough for me!

2017-04-24 18:47 UTC, mAAdhaTTah commented
@MichaelFoss I have no preference on the options. Which, if any, do you want to add?

2017-04-24 18:49 UTC, MichaelFoss approved these changes

2017-04-24 18:51 UTC, MichaelFoss commented
@mAAdhaTTah, was thinking things like `console.log` could be different from `console.warn` and `console.error`. Rethinking it though, I opted against it.

2017-04-24 18:51 UTC, mAAdhaTTah approved these changes

2017-04-24 18:51 UTC, mAAdhaTTah commented
@MichaelFoss + Me = 2 approvals, so merging this one.

2017-04-24 18:52 UTC, merged