Added vue.js config
valtech-nyc/eslint-config-valtech pull request #9
Opened 2017-10-24 12:49 UTC by timbenniks

Added dependencies: eslint-plugin-html, eslint-plugin-vue to makes sure .vue files can be linted.

2017-10-24 14:06 UTC, mAAdhaTTah requested changes
I'm in favor of this overall. Wondering if we should ship it more fleshed out than this to start or maybe building up the ruleset over time is a better approach.

2017-10-24 14:06 UTC, mAAdhaTTah commented on vue.js
> +};
Needs a newline at the end of the file.

2017-10-24 14:06 UTC, mAAdhaTTah commented on vue.js
> +        "vue/jsx-uses-vars": 2
Is this the only rule we want to enforce for now? Since we're just starting, it'll be easier to add rules now, rather than later.

2017-10-24 14:06 UTC, mAAdhaTTah commented on package.json
> +    "eslint-plugin-vue": "2.1.0"
I'd prefer `^` here, as it lets consumers get the latest version of the ruleset so they can add new rules we may not have configured yet.

Also, it looks the eslint plugin is in beta for `3.0.0`: https://github.com/vuejs/eslint-plugin-vue Maybe we want to get on this version now rather than needing to upgrade later?

2017-10-24 14:38 UTC, timbenniks commented on package.json
> +    "eslint-plugin-vue": "2.1.0"
Ok and Ok. Will change.

2017-10-24 14:39 UTC, timbenniks commented on vue.js
> +        "vue/jsx-uses-vars": 2
Currently this has been the only rule we have used in 6 months. The rest of the rules we adhere to is the native airbnb width some minor extensions. If you want I can put in all base VUE rules in here so we have a better overview?

2017-10-24 14:39 UTC, timbenniks commented on vue.js
> +};
Will change.

2017-10-24 15:39 UTC, mAAdhaTTah commented on vue.js
> +        'array-bracket-spacing': [2, 'never'],
I didn't mean to imply add all of the rules we're using in the main config file. I meant add all of the Vue-specific rules available in the Vue plugin. This configuration should be vue-only so people can compose a ruleset based on what tech they're using, e.g. `extends: 'valtech'` or `extends: ['valtech/vue,', 'valtech']` or eventually `extends: ['valtech/react,', 'valtech']`.

2018-01-04 16:56 UTC, mAAdhaTTah commented
Closing in favor of #10.

2018-01-04 16:56 UTC, closed without merging